Repository pointhi/kicad-footprint-generator, pull requests merged in 2019-10, with the labels that each got.

#132 Add the ability to mirror Text.
  KicadModTree/KicadFileHandler.py
  KicadModTree/nodes/base/Text.py
Labels: Pointhi pending

#426 Add QFN-64-1EP 9x9mm with 3.8x3.8mm EP
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/qfn-64_9x9.yaml
Labels: FP PR problem

#270 Add script for Hirose DF3EA-xxP-2H
  scripts/Connector/Connector_SMD_single_row_plus_mounting_pad/conn_hirose.yaml
Labels: ReadyForReview

#442 Molex sl171971
  scripts/Connector/Connector_Molex/conn_molex_stackable-linear_tht_top.py
Labels: Ready for review

#447 Add LFCSP_WD-10
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/lfcsp.yaml
Labels: Pending changes

#449 Adding TE 1734839 connectors
  scripts/Connector/Connector_TE-Connectivity/conn_fpc_te_1734839.py
Labels: Pending changes
