Repository pointhi/kicad-footprint-generator, pull requests merged in 2020-09, with the labels that each got.

#592 Derive pad size from IPC rules
  scripts/Packages/Package_BGA/ipc_7351b_bga_land_patterns.yaml
  scripts/Packages/Package_BGA/ipc_bga_generator.py
  scripts/Packages/Package_BGA/ipc_definitions.yaml
  scripts/Packages/Package_BGA/test_ipc.yaml
Labels: enhancement

#604 Support hidden and deleted pins
  KicadModTree/nodes/specialized/PadArray.py
  scripts/Packages/Package_Gullwing__QFP_SOIC_SO/ipc_gullwing_generator.py
  scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/soic.yaml
  scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/test_hidden_deleted_pins.yaml
  scripts/Packages/package_config_KLCv3.yaml
  scripts/tools/pad_number_generators.py
  scripts/tools/quad_dual_pad_border.py
Labels: enhancement

#628 Fix pin numbering in 1.5mm pitch Pico-Lock connectors (504050 series)
  scripts/Connector/Connector_SMD_single_row_plus_mounting_pad/conn_molex.yaml
Labels: bug

#612 Add WDFN-8 1EP 2x2mm EP0.8x1.2mm
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
Labels: Pending changes

#555 Added DFN-8-1EP package for MicroChip
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
Labels: Pending changes

#575 csp.yaml - Add X1-WLB0909 footprint
  scripts/Packages/Package_BGA/csp.yaml
Labels: enhancement

#642 Make Texas_WSON-N8 variants non vendor specific
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/wson.yaml
Labels: bug

#373 added DFN-14_1.35x3.5mm_P0.5mm
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
Labels: Pending changes

#643 Add WSON-8-1EP_4x4mm_P0.8mm_EP2.6x3mm
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/wson.yaml
Labels: enhancement

#619 Add VQFN-32-1EP_5x5mm_P0.5mm_EP3.15x3.15mm
  scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/vqfn.yaml
Labels: enhancement
